export type ColorObject = {
  argb: number
  hex: string
};

export type ColorName = 'primary'
| 'onPrimary'
| 'primaryContainer'
| 'onPrimaryContainer'
| 'secondary'
| 'onSecondary'
| 'secondaryContainer'
| 'onSecondaryContainer'
| 'tertiary'
| 'onTertiary'
| 'tertiaryContainer'
| 'onTertiaryContainer'
| 'success'
| 'onSuccess'
| 'successContainer'
| 'onSuccessContainer'
| 'warning'
| 'onWarning'
| 'warningContainer'
| 'onWarningContainer'
| 'error'
| 'onError'
| 'errorContainer'
| 'onErrorContainer'
| 'info'
| 'onInfo'
| 'infoContainer'
| 'onInfoContainer'
| 'background'
| 'onBackground'
| 'surface'
| 'onSurface'
| 'surfaceVariant'
| 'onSurfaceVariant'
| 'outline'
| 'outlineVariant'
| 'inverseSurface'
| 'inverseOnSurface'
| 'inversePrimary'
| 'shadow'
| 'scrim';
