import { Scheme, SchemeName, ThemeRef } from '../../types';

const darkSchemeFromRef = (ref: ThemeRef) => {
  return {
    primary: ref.primary[80],
    onPrimary: ref.primary[20],
    primaryContainer: ref.primary[30],
    onPrimaryContainer: ref.primary[90],
    secondary: ref.secondary[80],
    onSecondary: ref.secondary[20],
    secondaryContainer: ref.secondary[30],
    onSecondaryContainer: ref.secondary[90],
    tertiary: ref.tertiary[80],
    onTertiary: ref.tertiary[20],
    tertiaryContainer: ref.tertiary[30],
    onTertiaryContainer: ref.tertiary[90],
    success: ref.success[80],
    onSuccess: ref.success[20],
    successContainer: ref.success[30],
    onSuccessContainer: ref.success[90],
    warning: ref.warning[80],
    onWarning: ref.warning[20],
    warningContainer: ref.warning[30],
    onWarningContainer: ref.warning[90],
    error: ref.error[80],
    onError: ref.error[20],
    errorContainer: ref.error[30],
    onErrorContainer: ref.error[90],
    info: ref.info[80],
    onInfo: ref.info[20],
    infoContainer: ref.info[30],
    onInfoContainer: ref.info[90],
    background: ref.neutral[10],
    onBackground: ref.neutral[90],
    surface: ref.neutral[10],
    onSurface: ref.neutral[80],
    surfaceVariant: ref.neutralVariant[30],
    onSurfaceVariant: ref.neutralVariant[80],
    outline: ref.neutralVariant[60],
    outlineVariant: ref.neutralVariant[30],
    inverseSurface: ref.neutral[90],
    inverseOnSurface: ref.neutral[20],
    inversePrimary: ref.primary[40],
    shadow: ref.neutral[0],
    scrim: ref.neutral[0],
  };
};

const lightSchemeFromRef = (ref: ThemeRef): Scheme => {
  return {
    primary: ref.primary[40],
    onPrimary: ref.primary[100],
    primaryContainer: ref.primary[90],
    onPrimaryContainer: ref.primary[10],
    secondary: ref.secondary[40],
    onSecondary: ref.secondary[100],
    secondaryContainer: ref.secondary[90],
    onSecondaryContainer: ref.secondary[10],
    tertiary: ref.tertiary[40],
    onTertiary: ref.tertiary[100],
    tertiaryContainer: ref.tertiary[90],
    onTertiaryContainer: ref.tertiary[10],
    success: ref.success[40],
    onSuccess: ref.success[100],
    successContainer: ref.success[90],
    onSuccessContainer: ref.success[10],
    warning: ref.warning[40],
    onWarning: ref.warning[100],
    warningContainer: ref.warning[90],
    onWarningContainer: ref.warning[10],
    error: ref.error[40],
    onError: ref.error[100],
    errorContainer: ref.error[90],
    onErrorContainer: ref.error[10],
    info: ref.info[40],
    onInfo: ref.info[100],
    infoContainer: ref.info[90],
    onInfoContainer: ref.info[10],
    background: ref.neutral[99],
    onBackground: ref.neutral[10],
    surface: ref.neutral[99],
    onSurface: ref.neutral[10],
    surfaceVariant: ref.neutralVariant[90],
    onSurfaceVariant: ref.neutralVariant[30],
    outline: ref.neutralVariant[50],
    outlineVariant: ref.neutralVariant[80],
    inverseSurface: ref.neutral[20],
    inverseOnSurface: ref.neutral[95],
    inversePrimary: ref.primary[80],
    shadow: ref.neutral[0],
    scrim: ref.neutral[0],
  };
};

export const schemeFromRef = (schemeName: SchemeName, ref: ThemeRef) => {
  return schemeName === 'dark' ? darkSchemeFromRef(ref) : lightSchemeFromRef(ref);
};
