import { ThemeSys } from '../../types';

const defaultFontFamily: string[] = [
  'Inter',
  'system-ui',
  '-apple-system',
  'BlinkMacSystemfontFamily',
  '"Segoe UI"',
  'Oxygen',
  'Ubuntu',
  'Cantarell',
  '"Open Sans"',
  '"Helvetica Neue"',
  'sans-serif',
];

export const DEFAULT_SYS: ThemeSys = {
  typescale: {
    display: {
      large: {
        fontFamily: defaultFontFamily,
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: '3.5625rem',
        lineHeight: '4rem',
        letterSpacing: '-0.015625rem',
      },
      medium: {
        fontFamily: defaultFontFamily,
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: '2.8125rem',
        lineHeight: '3.25rem',
        letterSpacing: '0',
      },
      small: {
        fontFamily: defaultFontFamily,
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: '2.25rem',
        lineHeight: '2.75rem',
        letterSpacing: '0',
      },
    },
    headline: {
      large: {
        fontFamily: defaultFontFamily,
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: '2rem',
        lineHeight: '2.5rem',
        letterSpacing: '0',
      },
      medium: {
        fontFamily: defaultFontFamily,
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: '1.75rem',
        lineHeight: '2.25rem',
        letterSpacing: '0',
      },
      small: {
        fontFamily: defaultFontFamily,
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: '1.5rem',
        lineHeight: '2rem',
        letterSpacing: '0',
      },
    },
    title: {
      large: {
        fontFamily: defaultFontFamily,
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: '1.375rem',
        lineHeight: '1.75rem',
        letterSpacing: '0',
      },
      medium: {
        fontFamily: defaultFontFamily,
        fontStyle: 'normal',
        fontWeight: '500',
        fontSize: '1rem',
        lineHeight: '1.5rem',
        letterSpacing: '0.009375rem',
      },
      small: {
        fontFamily: defaultFontFamily,
        fontStyle: 'normal',
        fontWeight: '500',
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
        letterSpacing: '0.00625rem',
      },
    },
    label: {
      large: {
        fontFamily: defaultFontFamily,
        fontStyle: 'normal',
        fontWeight: '500',
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
        letterSpacing: '0.00625rem',
      },
      medium: {
        fontFamily: defaultFontFamily,
        fontStyle: 'normal',
        fontWeight: '500',
        fontSize: '0.75rem',
        lineHeight: '1rem',
        letterSpacing: '0.03125rem',
      },
      small: {
        fontFamily: defaultFontFamily,
        fontStyle: 'normal',
        fontWeight: '500',
        fontSize: '0.6875rem',
        lineHeight: '1rem',
        letterSpacing: '0.03125rem',
      },
    },
    body: {
      large: {
        fontFamily: defaultFontFamily,
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: '1rem',
        lineHeight: '1.5rem',
        letterSpacing: '0.03125rem',
      },
      medium: {
        fontFamily: defaultFontFamily,
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
        letterSpacing: '0.015625rem',
      },
      small: {
        fontFamily: defaultFontFamily,
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: '0.75rem',
        lineHeight: '1rem',
        letterSpacing: '0.025rem',
      },
    },
  },
  motion: {
    easing: {
      linear: '0, 0, 1, 1',
      standard: '0.2, 0, 0, 1',
      standardAccelerate: '0.3, 0, 1, 1',
      standardDecelerate: '0, 0, 0, 1',
      emphasized: '0.2, 0, 0, 1',
      emphasizedAccelerate: '0.3, 0, 0.8, 0.15',
      emphasizedDecelerate: '0.05, 0.7, 0.1, 1',
      legacy: '0.4, 0, 0.2, 1',
      legacyAccelerate: '0.4, 0, 1, 1',
      legacyDecelerate: '0, 0, 0.2, 1',
    },
    duration: {
      short1: 50,
      short2: 100,
      short3: 150,
      short4: 200,
      medium1: 250,
      medium2: 300,
      medium3: 350,
      medium4: 400,
      long1: 450,
      long2: 500,
      long3: 550,
      long4: 600,
      extraLong1: 700,
      extraLong2: 800,
      extraLong3: 900,
      extraLong4: 1000,
    },
  },
  shape: {
    none: '0',
    extraSmall: ' 0.25rem',
    small: '0.5rem',
    medium: '0.75rem',
    large: '1rem',
    extraLarge: '1.75rem',
    full: '9999px',
  },
};
