name: Coverage
 
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
 
jobs:
  build:
    name: Test and Create Badge
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .npmrc
        run: |
            echo "//npm.pkg.jetbrains.space/bruhabruh/p/envie/npm/:_authToken=${{ secrets.SPACE_TOKEN }}" >> ~/.npmrc
            echo "@envie:registry=https://npm.pkg.jetbrains.space/bruhabruh/p/envie/npm/" >> ~/.npmrc

      - name: Install dependencies
        run: npm ci

      - name: Coverage
        run: npm run coverage

      - name: Get total percent
        id: percent
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: './coverage/coverage-summary.json'
          prop_path: 'total.lines.pct'

      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 96bdbce4d06b5692e89d42106c98eca9
          filename: envie-theme.json
          label: Test Coverage
          message: ${{steps.percent.outputs.prop}}
          color: '#6E9F18'
          namedLogo: vitest